Big update with installer

diff --git a/ren0-install b/ren0-install
--- a/ren0-install
+++ b/ren0-install
@@ -33,7 +33,7 @@ logo () {
             printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}" 
 }
 
-if [ "$(id -u)" = 0 ]; then
+if [ "$EUID" -ne 0 ]; then
     echo "This is script must be run as root"
     exit 1
 fi
@@ -44,7 +44,6 @@ sleep 3
 clear 
 
 logo "Installing needed packages..."
-
 
 dependencias=(base-devel rustup pacman-contrib bspwm polybar sxhkd \
 			  alacritty brightnessctl dunst rofi lsd stalonetray \
@@ -82,22 +81,22 @@ logo "Downloading dotefiles"
 repo_url="https://github.com/0SU2/dotefiles.git"
 repo_dir="$HOME/dotfiles"
 
-# verificar si el directorio del repositorio ya existe y, si es asi, lo elimina
+# Check if the repository is already copy, if its copy already then is delete
     if[ -d "$repo_dir" ]; then
-        printf "Removing eixsting dotfiles repository\n"
+        printf "%sRemoving eixsting dotfiles repository%s\n" "${CRE}" "${CNC}"
         rm -rf "$repo_dir"
     fi
 
-# CLona el repositorio
-printf "Cloning dotfiles from %s\n" "$repo_url"
+# Clone the repository
+printf "Cloning dotfiles from %s%s%s%s\n" "${CGR}" "${BLD}" "$repo_url" "${CNC}"
 git clone --depth=1 "$repo_url" "$repo_dir"
 
-sleep 2
+sleep 3
 clear
 
 # --- Copy the rice ---
 logo "Installing dotfiles..."
-printf "Copying files to respective directories..\n"
+printf "%sCopying files to respective directories..%s\n" "${BLD}" "${CNC}"
 
 [ ! -d ~/.config ] && mkdir ~/.config
 [ ! -d ~/.local ] && mkdir ~/.local
@@ -105,16 +104,33 @@ printf "Copying files to respective directories..\n"
 [ ! -d ~/.local/share/applications ] && mkdir ~/.local/share/applications
 [ ! -d ~/.local/share/fonts ] && mkdir ~/.local/share/fonts
 [ ! -d ~/Pictures ] && mkdir ~/Pictures
-[ ! -d ~/Pictures/Wallpapers ] && ~/Pictures/Wallpapers
+[ ! -d ~/Pictures/Wallpapers ] && mkdir ~/Pictures/Wallpapers
 
-for 
+# copy files inside their corresponding directory
+printf "Coping files from %s/dotfiles/.config%s to your %s.config%s directory" "${CGR}" "${CNC}" "${CRE}" "${CNC}"
+for files in ~/dotfiles/.config/*;
+do
+    cp -ru ${files} ~/.config
+done
+
+printf "Coping files from %s/dotfiles/.local%s to your %s.local%s directory" "${CGR}" "${CNC}" "${CRE}" "${CNC}"
+for files in ~/dotfiles/.local/bin/*;
+do
+    cp -ru ${files} ~/.local
+done
+
+printf "Coping files from %s/dotfiles/Pictures%s to your %sPictures%s directory" "${CGR}" "${CNC}" "${CRE}" "${CNC}"
+for files in ~/dotfiles/Pictures;
+do
+    cp -ru ${files} ~/Pictures
+done
 
 fc-cache -rv >/dev/null 2>&1
 printf "%s%sFiles copied succesfully!!%s\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 3
 
 # ----- Installing paru & others ------ #
-logo "Installing Paru, Eww, tdrop & xqp"
+logo "Installing Paru, Eww and yay"
 
 # Installing Paru
     if command -v paru >/dev/null 2>&1; then
@@ -131,13 +147,19 @@ logo "Installing Paru, Eww, tdrop & xqp"
         }
     fi
 
-# Installing xqpp
-    if command -v xqp >/dev/null 2>&1; then
-        printf "\n%s%sxqp is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
-    else 
-        printf "\n%s%sInstalling xqp, this should be fast!%s\n" "${BLD}" "${CGR}" "${CNC}"
-        paru -S xqp --skipreview --noconfirm
-    fi
+# Installing yay
+    if command -v yay > /dev/null 2>&1; then
+        printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+    else
+        printf "%s%sInstalling paru%s\n" "${CYE}" "${BLD}" "${CNC}"
+        {
+            cd "$HOME" || exit
+            git clone https://aur.archlinux.org/yay.git
+            cd yay || exit
+            makepkg -si --noconfirm
+        } || {
+            printf "\n%s%sFailed to install Paru, You may need to install it manually%s\n" "${BLD}" "${CGR}" "${CNC}" 
+        }
 
 # Installing eww
     if command -v eww >/dev/null 2>&1; then
